### ISSUE TITLE
Mixed content blocked

### ISSUE THREAD

**Issue by JStrebeyko** [rosshettel/jelloearth#1]
Hi there @rosshettel ,

Absolutely :heart:d your APIs and the online resume. :+1: 
Be informed, though, that the `jellorearth` showcase is not working, because loading of d3 gets blocked. Here, I'll let them speak through me:
>Mixed Content: The page at 'https://rosshettel.github.io/jelloearth/' was loaded over HTTPS, but requested an insecure script 'http://d3js.org/topojson.v0.min.js'. This request has been blocked; the content must be served over HTTPS.

Really curious to see what is it all about! :)

Sending best regards! :beers:

**Comment by rosshettel** [comment]
Ah thanks for the heads up, wrote that a while ago before GH pages supported HTTPS so the link to d3 was over HTTP. Just pushed a fix so you should be able to check it out now. Cheers!

**Comment by JStrebeyko** [comment]
haha it's jello indeed! great job! :icecream:
